-- ============================================================================
-- MIGRATION: Table report_requests for Server-Side PDF Report Queue
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.report_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nim TEXT NOT NULL,
  nama_lengkap TEXT,
  drive_folder_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  pdf_url TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index for fast queries by NIM and status
CREATE INDEX IF NOT EXISTS idx_report_requests_nim ON public.report_requests (nim);
CREATE INDEX IF NOT EXISTS idx_report_requests_status ON public.report_requests (status);

-- Enable Row Level Security (RLS)
ALTER TABLE public.report_requests ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for checking status)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'report_requests' AND policyname = 'Allow public read access to report_requests'
  ) THEN
    CREATE POLICY "Allow public read access to report_requests"
      ON public.report_requests
      FOR SELECT
      USING (true);
  END IF;
END $$;

-- Allow public insert access (for queueing request)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'report_requests' AND policyname = 'Allow public insert access to report_requests'
  ) THEN
    CREATE POLICY "Allow public insert access to report_requests"
      ON public.report_requests
      FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

-- Allow update access (for Edge function / worker)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'report_requests' AND policyname = 'Allow public update access to report_requests'
  ) THEN
    CREATE POLICY "Allow public update access to report_requests"
      ON public.report_requests
      FOR UPDATE
      USING (true);
  END IF;
END $$;
